---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
  namespace: backup-solution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: docker.io/nextcloud
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: backup-solution
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: tcp
  selector:
    app: nextcloud
--------
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nextcloud-ingress
  namespace: backup-solution
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud-service
          servicePort: 8080