---
# Mariadb persistent local volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-storage
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /persistent_volume_storage/cluster/mariadb
---
# Nextcloud persistent local volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-storage
  labels:
    type: local
spec:
  capacity:
    storage: 995Gi
  volumeMode: Filesystem
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /persistent_volume_storage/cluster/nextcloud
---
# Mariadb storage claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-storage-claim
  namespace: backup-solution
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: mariadb-storage
---
# Nextcloud storage claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-storage-claim
  namespace: backup-solution
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 995Gi
  volumeName: nextcloud-storage
---
# Mariadb deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: backup-solution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
        - name: mariadb-storage-vol
          persistentVolumeClaim:
            claimName: mariadb-storage-claim
      containers:
        - name: mariadb
          image: docker.io/library/mariadb
          ports:
          - containerPort: 3306
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: "/var/lib/mysql"

            name: mariadb-storage-vol
---
# Nextcloud deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
  namespace: backup-solution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
        - name: nextcloud-storage-vol
          persistentVolumeClaim:
            claimName: nextcloud-storage-claim
      containers:
        - name: nextcloud
          image: docker.io/library/nextcloud
          ports:
          - containerPort: 80
          imagePullPolicy: Always
          env:
          - name: MYSQL_HOST
            value: mariadb
          - name: MYSQL_USER
            value: nextcloud
          - name: MYSQL_PASSWORD
            value: nextcloud
          - name: MYSQL_DATABASE
            value: nextcloud
          volumeMounts:
            - mountPath: "/var/www/html"
              name: nextcloud-storage-vol
---
# Nodeport service to access nextcloud
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: backup-solution
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: tcp
    nodePort: 30001
  selector:
    app: "nextcloud"